config/routes.rb
Carbay::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  if Rails.env.development?
    mount RailsEmailPreview::Engine, :at => 'email_preview' # You can choose any URL here
  end

  resources :requests do
    resources :bids, only: [:new, :create, :index] 
  end

  resources :bids do
      member do
        get 'winner'
      end
  end

  resources :makes, only: [:index]
  resources :models, only: [:index] do
    member do
      get :years
    end
  end
  resources :cars, only: [:index] do
    collection do
      get 'style', action: :style, as: 'style'
    end
  end

  devise_for :users
  #ActiveAdmin.routes(self)

  resources :customers, only: [:update, :edit] do
  end

  get "dash" => "requests#index", as: 'dash'
  
  #root :to => 'high_voltage/pages#show', :id => 'home'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  root :to => 'pages#show', :id => 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  attr_accessible :amount, :dealer_id, :other_offers, :request_id
  belongs_to :request
  belongs_to :dealer

  after_create :after_create

  validates :amount, :numericality => { :only_integer => true, message: "must be an integer, format it like this 19900, instead of $19,0000" }

  def after_create
    #Mail to the user
    UserMailer.new_bid(self.request.customer, self).deliver
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
    before_filter :authenticate_user!
  # GET /bids
  # GET /bids.json

  def winner
    bid = Bid.find(params[:id])
    if bid
      bid.won = true
      bid.save
      bid.request.status = 'Closed'
      bid.request.save
      DealerMailer.won_request(bid).deliver
    end
  end

  def index
    @bids = current_user.profileable.available_requests.includes([:make, :model])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/new
  # GET /bids/new.json
  def new
    @request = Request.find(params['request_id'])
    @bid = Bid.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/1/edit
  def edit
    @bid = bid.find(params[:id])
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(params[:bid])
    @bid.dealer_id = current_user.profileable.id
    @request = @bid.request
    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid.request, notice: 'Your bid is now live! The customer who requested the bid has been notified. Wait until they choose a winner or make another bid!' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
    @bid = bid.find(params[:id])

    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid = bid.find(params[:id])
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bids_for_request.html.haml
%table.bordered
  %thead
    %tr
      %th Amount
      %th Date
      %th Other Notes
      %th Winning Bid?
      - if current_user.customer? and request.not_won?
        %th Select Winner
      - if current_user.dealer?
        %th Your Bid?
  %tbody
    - @bids.each do |bid|
      %tr
        %td
          = number_to_currency(bid.amount, unit: "$")
        %td
          = bid.updated_at
        %td
          = bid.other_offers
        %td
          = bid.won
        - if current_user.customer? and request.not_won?
          %td 
            - if current_user.profileable.first_name.blank? or current_user.profileable.last_name.blank? or current_user.profileable.phone_number.blank?
              -# %a.fancybox{href: edit_customer_path(id: current_user.profileable.id, request_id: request.id)} Select Winner
              = link_to "Select Winner", edit_customer_path(id: current_user.profileable.id, request_id: request.id)
            - else
              = link_to "Select Winner", winner_bid_path(bid), data: { confirm: 'Are you sure?  If you say yes your contact information will be sent to the dealer!' }
        - if current_user.dealer? and current_user.profileable.id == bid.dealer_id 
          %td
            Yes
        - elsif current_user.dealer?
          %td
            No

app/views/bids/_form.html.haml
= form_for(@bid, :html => {:class => 'form-horizontal'}) do |f|
  .control-group
    - if @bid.errors.any? 
      .error_explanation
        %h2
          = pluralize(@bid.errors.count, "error")
          prohibited this request from being saved:</h2>
        %ul
          - @bid.errors.full_messages.each do |msg| 
            %li
              = msg
    %h1 Request Information
    = render '/requests/show', request: @request
    .field
      = f.label "Bid Amount", class: 'control-label'
      = f.text_field :amount
    .field
      = f.label "Other Offers to Customer", class: 'control-label'
      = f.text_area :other_offers

    = f.hidden_field :request_id, :value => @request.id
    .controls
      .actions
        %br
        = f.submit

app/views/bids/edit.html.haml
= render 'form'

app/views/bids/new.html.haml
= render 'form'

app/views/bids/winner.html.haml
.winning
  %h1
    Congratulations! You have selected your winning bid.  
  %p
    Your information has been sent to the dealer who made the winning bid.  Expect to hear back from them within 24 hours!