config/routes.rb
Carbay::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  if Rails.env.development?
    mount RailsEmailPreview::Engine, :at => 'email_preview' # You can choose any URL here
  end

  resources :requests do
    resources :bids, only: [:new, :create, :index] 
  end

  resources :bids do
      member do
        get 'winner'
      end
  end

  resources :makes, only: [:index]
  resources :models, only: [:index] do
    member do
      get :years
    end
  end
  resources :cars, only: [:index] do
    collection do
      get 'style', action: :style, as: 'style'
    end
  end

  devise_for :users
  #ActiveAdmin.routes(self)

  resources :customers, only: [:update, :edit] do
  end

  get "dash" => "requests#index", as: 'dash'
  
  #root :to => 'high_voltage/pages#show', :id => 'home'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  root :to => 'pages#show', :id => 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :make_id, :model_id, :notes, :style, :user_id, :year, 
    :leather,   :navigation,     :premium_sound,     :backup_camera,    :reverse_sensor,
    :heated_seats,    :sun_roof,   :awd,    :keyless_ignition,    :remote_start,
    :bluetooth,    :tow_package, :style_id, :option_ids

  default_scope order('requests.created_at DESC')

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  has_many :available_dealers, through: :make, source: "dealers"
  belongs_to :style
  
  has_many :car_options
  has_many :options, through: :car_options

  has_one :winning_bid, class_name:'Bid', conditions:  "bids.won = 'true'"

  has_many :bids
  has_many :unique_bids, class_name: 'Bid', :finder_sql => proc { "SELECT bids.* FROM bids where request_id = #{id} and bids.id in (select max(bids2.id) from bids bids2 where bids2.request_id = bids.request_id group by bids2.dealer_id)" }

  #scope :winner, includes(:bid).where(won: true).limit(1)

  after_create :after_create

  self.per_page = 5

  def name
    self.year.to_s + ' ' + self.make.name + ' ' + self.model.name 
  end

  def after_create
    #Mail to all dealers
    dealers = self.available_dealers
    dealers.each do |dealer|
      DealerMailer.new_request(dealer, self).deliver
    end
  end

  def not_won?
    won_bids = self.bids.where(won: true)
    won_bids.blank?
  end

  def won?
    won_bids = self.bids.where(won: true)
    won_bids.present?
  end

  def photo
    self.style.photo
  end

  def get_options
    self.options.map(&:name).join(', ')
  end

  def has_new_bids
    if self.bids.present?
      return self.bids.order("created_at desc").first.created_at > (Time.now - 1.day)
    else
      false
    end
  end

  def did_i_bid_on_it?(user)
    if self.bids.present?
      "Yes" if self.bids.where(dealer_id:user.profileable.id).count > 0
    else
      "No"
    end
  end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_user!
  # GET /requests
  # GET /requests.json
  def index
    if current_user.customer?
      @requests = current_user.profileable.requests.includes([:make, :model, :style, :bids, :options]).paginate(:page => params[:page])
      render "customer_index"
    elsif current_user.dealer?
      @requests = current_user.profileable.available_requests.includes([:make, :model, :style, :bids, :options]).paginate(:page => params[:page], :per_page => 20)
      render "dealer_index"
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    if current_user.dealer?
      @request = Request.includes(:bids).find_by_id(params[:id])
      @bids = @request.unique_bids if @request
    elsif current_user.customer?
      @request = current_user.profileable.requests.includes(:bids).find_by_id(params[:id])
      @bids = @request.unique_bids if @request
    end


    if @request.blank?
      respond_to do |format|
        format.html { redirect_to requests_path(), notice: 'Sorry, perhaps that request removed or you do not have access to view it!' }
      end
      
    else
      @bids = [] if @bids.blank?
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @request }
      end
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    @makes = Make.new_makes
    @models = []
    @styles = []

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])
    @request.customer_id = current_user.profileable.id
    @request.year = Model.find(params[:request][:model_id]).newest_year
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
= form_for(@request, :html => {:class => 'form-horizontal'}) do |f|
  .control-group
    - if @request.errors.any?
      .error_explanation
        %h2
          = pluralize(@request.errors.count, "error")
          prohibited this request from being saved:
        %ul
          = @request.errors.full_messages.each do |msg|
            %li
              = msg
    .fields
      = f.label :make_id, 'Make: ', class: 'control-label' 
      = collection_select :request, :make_id, @makes, :id, :name, :input_html => {:rel => "/makes/models_by_make"}
    .fields
      = f.label :model_id, 'Model: ', class: 'control-label' 
      = collection_select :request, :model_id, [], :id, :name
    .fields
      = f.label :year, 'Year: ', class: 'control-label'
      = collection_select :request, :year, [], :year, :year
    .fields
      = f.label :style_id, 'Style: ', class: 'control-label'
      = collection_select :request, :style_id, [], :id, :name
    .fields
      = f.label :option_ids, 'Options: ', class: 'control-label'
      = f.collection_select :option_ids, Option.order(:name), :id, :name, {}, {multiple: true}
    .fields
      = f.label :notes, 'Notes: ', class: 'control-label'
      = f.text_area :notes, class: 'text_area_big'
    .controls
      .actions
        = f.submit

app/views/requests/_show.html.haml
%h1.car_name
  = @request.name
.sub_header_text
  = request.style.name
= image_tag(request.photo, alt: request.name, size: "200x200", class: "car_photo")
.info_block
  %span.emphasized
    Options:
  = request.get_options
.info_block.clear
  %span.emphasized
    Notes:
  = request.notes

app/views/requests/customer_index.html.haml
.page_container
  %h1 Your Requests
  = will_paginate @requests
  %ul
    - @requests.each do |request|
      %li
        .request_car_display_box
          .car_photo
            = link_to image_tag(request.photo, :alt => request.name, :size => "200x200"),  request_path(request)
          .request_info
            %span.header
              = link_to request.name, request_path(request)
              = '(' + request.bids.count.to_s  + ')'
            - if request.has_new_bids 
              %span.label
                New Bids
            .info_block
              %span.emphasized
                Status:
              = request.status
            .info_block
              %span.emphasized
                Options:
              = request.get_options
            .info_block
              %span.emphasized
                Notes:
              = request.notes
          .relative_container
            .request_delete
              = link_to 'Delete Request', request, method: :delete, data: { confirm: 'Are you sure?' }
      .clear

app/views/requests/dealer_index.html.haml
%h1 Available Requests
= will_paginate @requests
%table.bordered
  %thead
    %th Created
    %th Make
    %th Model
    %th Year
    %th Status
    %th Did I bid?
    %th # of Bids
    %th Notes    
  %tbody
    - @requests.each do |request|
      %tr
        %td 
          = link_to request.created_at.strftime("%m/%d/%Y"), request_path(request)
        %td 
          = link_to request.make.name, request_path(request)
        %td 
          = link_to request.model.name, request_path(request)
        %td 
          = link_to request.year, request_path(request)
        %td 
          = link_to request.status, request_path(request)
        %td 
          = link_to request.did_i_bid_on_it?(current_user), request_path(request)
        %td 
          = link_to request.bids.count, request_path(request)
        %td 
          = link_to request.notes, request_path(request)

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class="page_container">         
  <h1>Your Available Requests</h1>
  <table>
    <tr>
      <th>User</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Notes</th>
      <th></th>
    </tr>

  <% @requests.each do |request| %>
    <div class="a_row">
    </div>
      <td><%= request.customer_id %></td>
      <td><%= request.make.name %></td>
      <td><%= request.model.name %></td>
      <td><%= request.year %></td>
      <td><%= request.notes %></td>
      <td><%= link_to 'Show', request %></td>
    </tr>
  <% end %>
  </table>

  <br />

</div>

app/views/requests/new.html.haml
%br
%h1 Find Your Car in Three Easy Steps
#spinner
  = image_tag("loading.gif", alt: "Loading Gif", size: "100x100", class: "top_centered")
= render 'form'

app/views/requests/show.html.haml
.page_container.subpage_specific_container
= render 'show', request: @request
%h2
  Bid listing : all dealers
- if @bids.blank?
  %p
    You have not bid yet! 
    %br
    - if current_user.dealer? and @request.not_won?
      = link_to "Bid on this Request", new_request_bid_path(request_id:@request.id ,dealer_id:current_user.profileable.id), class: "button button-primary button-large"
- else
  %p
    = render '/bids/bids_for_request', request: @request
    %br
    - if current_user.dealer? and @request.not_won?
      = link_to "Bid Again on this Request", new_request_bid_path(request_id:@request.id ,dealer_id:current_user.profileable.id), class: "button button-primary button-large"