config/routes.rb
Carbay::Application.routes.draw do
  require 'sidekiq/web'

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  if Rails.env.development?
    mount RailsEmailPreview::Engine, :at => 'email_preview' # You can choose any URL here
  end

  resources :requests do
    resources :bids, only: [:new, :create, :index] 
  end

  resources :bids do
      member do
        get 'winner'
      end
  end

  resources :makes, only: [:index]
  resources :models, only: [:index] do
    member do
      get :years
    end
  end
  resources :cars, only: [:index] do
    collection do
      get 'style', action: :style, as: 'style'
    end
  end

  devise_for :users
  #ActiveAdmin.routes(self)

  resources :customers, only: [:update, :edit] do
  end

  get "dash" => "requests#index", as: 'dash'
  
  #root :to => 'high_voltage/pages#show', :id => 'home'
  get "/pages/*id" => 'pages#show', :as => :page, :format => false
  root :to => 'pages#show', :id => 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/_footer.html.erb
<ul class="footer">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "How It Works", page_path('howitworks') %></li>
  <li><%= link_to "About", page_path('about') %></li>
  <% if user_signed_in? %>
    <% if current_user.customer? %>
      <li><%= link_to "New Request", new_request_path %></li>
    <% end %>
    <li>   
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <li>
    <%= link_to('Logout' , destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>
<br />
Copyright &copy;  Carmedius.com

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag('carmedius_logo_notagline.png'), root_path, :class => 'header-logo' %>
<ul class="nav">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "How It Works", page_path('howitworks') %></li> 
  <% if user_signed_in? %>
    <% if current_user.customer? %>
      <li><%= link_to "New Request", new_request_path %></li>
    <% end %>
    <li>   
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <li>
    <%= link_to('Logout' , destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Carmedius" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] if Carbay::Application.assets.find_asset("#{params[:controller]}") %>
    <%= javascript_include_tag "#{params[:controller]}_#{params[:action]}"  if Carbay::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}") %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render partial: "shared/flash_messages", flash: flash %> 
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <!-- <div class="footer-clear"><br /><br /></div> -->
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Carmedius" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] if Carbay::Application.assets.find_asset("#{params[:controller]}") %>
    <%= javascript_include_tag "#{params[:controller]}_#{params[:action]}"  if Carbay::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}") %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render partial: "shared/flash_messages", flash: flash %> 
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/no_header.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Carmedius" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] if Carbay::Application.assets.find_asset("#{params[:controller]}") %>
    <%= javascript_include_tag "#{params[:controller]}_#{params[:action]}"  if Carbay::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}") %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class = 'no_header_body'>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render partial: "shared/flash_messages", flash: flash %> 
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>